coverage:
  range: 50..100
  status:
    project:
      default: off
      xcallbackurl:
        flags: xcallbackurl
      xcallbackurl_bear:
        flags: xcallbackurl_bear

flags:
  xcallbackurl:
    paths:
      - packages/xcallbackurl/lib/
  xcallbackurl_bear:
    paths:
      - packages/xcallbackurl_bear/lib/