name: xcallbackurl
version: 0.1.1
description: >-
  Base classes that support the construction x-callback-url URL schemas
  for inter-app communication and messaging on Apple’s iOS/Mac platforms.
homepage: https://github.com/ivoleitao/xcallbackurl
repository: https://github.com/ivoleitao/xcallbackurl
issue_tracker: https://github.com/ivoleitao/xcallbackurl/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7