name: xcallbackurl_bear
version: 0.1.1
description: >-
  Support for the construction x-callback-url URL schemas for Bear.
homepage: https://github.com/ivoleitao/xcallbackurl
repository: https://github.com/ivoleitao/xcallbackurl
issue_tracker: https://github.com/ivoleitao/xcallbackurl/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  xcallbackurl: ^0.1.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7