name: xcallbackurl_bear
version: 1.0.0
description: >-
  Support for the construction x-callback-url URL schemas for Bear.
homepage: https://github.com/ivoleitao/xcallbackurl
repository: https://github.com/ivoleitao/xcallbackurl
issue_tracker: https://github.com/ivoleitao/xcallbackurl/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  xcallbackurl: ^1.0.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7