name: Dart Coverage

on:
  push:
    branches:
      - master
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/dart-coverage.yml'

jobs:
  coverage:
    name: Dart Coverage

    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          dart pub global activate melos

      - name: Bootstrap
        run: |
          melos bs

      - name: Coverage
        run: |
          melos coverage
          melos codecov